### PR TITLE
Fix lag caused by empty crafting table and Update to 1.18.2

### LINKED ISSUE #6: Shift Clicking a recipe from the crafting table will craft something else using the items that remain.
For example if you craft a Smithing Table with extra iron in the crafting grid you will get a bunch of pressure plates, I suppose that the reason why this is happening is because that is the way it works if you are auto crafting using a hopper but I feel like this shouldn't apply to the normal crafting system.

### LINKED ISSUE #54: Update to 1.18.2
Could you update this extension to 1.18.2? Would be much appreciated.

### PR DESCRIPTION
**Pull request by Crec0**
Empty crafting tables sitting on hoppers were causing tremendous lag due to recipe manager being invoked every tick to search for empty recipes.  
Since crafting tables were empty, there's no need to check for recipes, we can exit early.  
Update to 1.18.2 while at it.
resolves #54 
fixes #6

### CODE REVIEW

**Comment by DanShaders** [comment]
Shift clicking output slot does not work with your fix.
Adding `return this.blockEntity.getStack(0);` after 125th line in AutoCraftingTableContainer.java makes it work again, however I am not sure if it does not break anything else.

**Comment by Crec0** [comment]
@DanShaders Can you try now ?

**Comment by DanShaders** [comment]
Yeap, both commits work.

**Comment by DanShaders** [comment]
Well, I found another bug: shift clicking output crafts till there is no available products even if the recipe has changed.
For example, clicking with shift on sticks here
before
results in buttons and sticks crafted
after
(This is not the case with commit 4e1b13b)

**Comment by Crec0** [comment]
@DanShaders I really appreciate the feedback so far. Thank you. I have fixed this issue.

**Comment by DanShaders** [comment]
Oh, I thought it was an issue with your new code but apparently you've fixed #6)

**Comment by Crec0** [comment]
Didn't even realize it was an existing issue. Well as long as it's fixed :shrug:

**Pull request merged**
