### PR TITLE
Update to 1.19

### LINKED ISSUE #6: Shift Clicking a recipe from the crafting table will craft something else using the items that remain.
For example if you craft a Smithing Table with extra iron in the crafting grid you will get a bunch of pressure plates, I suppose that the reason why this is happening is because that is the way it works if you are auto crafting using a hopper but I feel like this shouldn't apply to the normal crafting system.

### LINKED ISSUE #55: 1.19 support
When can we expect 1.19 support?

### PR DESCRIPTION
**Pull request by Crec0**
Updates the mod to 1.19
Bump version number

Depends on #53 
Resolves #55 
Fixes #6

### CODE REVIEW

**Comment by codemonkey76** [comment]
Any chance i can get a jar file with this merged, i don't know anything about compiling with java :-)

**Comment by Crec0** [comment]
https://github.com/Crec0/carpet-autoCraftingTable/actions/runs/2498506836

Get it from github actions from my fork

**Comment by codemonkey76** [comment]
> https://github.com/Crec0/carpet-autoCraftingTable/actions/runs/2498506836
> 
> Get it from github actions from my fork

Legend, thanks!, I got it working.

**Comment by kosma** [comment]
@gnembon, what's the official word on your support for this mod? "Abandoned" or "lack of time" is fine, just please say anything :)

**Comment by DarianLStephens** [comment]
Is there a 1.18.2 build of this available with the empty table lag fix?

**Comment by Crec0** [comment]
> Is there a 1.18.2 build of this available with the empty table lag fix?

@DarianLStephens https://github.com/Crec0/carpet-autoCraftingTable/actions/runs/2539794409

**Pull request merged**
